name: Build bottles.

on:
  pull_request:
    paths:
      - 'Formula/*'

jobs:
  build-bottles:
    strategy:
      matrix:
        version: [10.15, 10.14, 10.13]
    runs-on: ${{ matrix.version }}
    env:
      HOMEBREW_GIT_NAME: BrewTestBot
      HOMEBREW_GIT_EMAIL: 'homebrew-test-bot@lists.sfconservancy.org'
      PATH: '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED: 1
    steps:
      - name: Checkout repository
        run: |
          cd $(brew --repo ${{github.repository}})
          git fetch origin ${{github.sha}}
          git reset --hard ${{github.sha}}
      - name: Build bottles
        run: |
          mkdir bottles
          cd bottles
          brew test-bot
      - name: Count bottles
        id: bottles
        if: always()
        run: |
          cd bottles
          count=$(ls *.json | wc -l | xargs echo -n)
          echo "$count bottles"
          echo "::set-output name=count::$count"
      - name: Upload bottles
        if: steps.bottles.outputs.count > 0
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: bottles
      - name: Cleanup
        if: always()
        run: |
          find .
          rm -rf *
