name: Build bottles.

on:
  pull_request:
    paths:
      - 'Formula/*'

jobs:
  build-bottles:
    strategy:
      matrix:
        version: [10.15, 10.14, 10.13]
    runs-on: ${{ matrix.version }}
    env:
      HOMEBREW_GIT_NAME: BrewTestBot
      HOMEBREW_GIT_EMAIL: 'homebrew-test-bot@lists.sfconservancy.org'
      PATH: '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED: 1
    steps:
      - name: Checkout repository
        run: |
          cd $(brew --repo ${{github.repository}})
          git fetch origin ${{github.sha}}
          git reset --hard ${{github.sha}}
      - name: Customize brew-test-bot
        run: |
          cd $(brew --repo homebrew/test-bot)
          git fetch origin refs/pull/328/merge
          git reset --hard FETCH_HEAD
      - name: Build bottles
        run: |
          mkdir bottles
          cd bottles
          brew test-bot
      - name: Uncustomize brew-test-bot
        if: always()
        run: |
          brew update-reset $(brew --repo homebrew/test-bot)
      - name: Count bottles
        id: bottles
        if: always()
        run: |
          cd bottles
          count=$(ls *.json | wc -l | xargs echo -n)
          echo "$count bottles"
          echo "::set-output name=count::$count"
      - name: Upload bottles
        if: steps.bottles.outputs.count > 0
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: bottles
      - name: Cleanup
        if: always()
        run: |
          BREW_LIST=$(brew list 2>/dev/null)
          if [ -n "$BREW_LIST" ]; then
            echo ">> brew uninstall"
            brew uninstall --force --ignore-dependencies $BREW_LIST
            echo "::warning::brew test-bot didn't clean up after itself"
          fi
          find .
          rm -rf *
